import 'package:flutter/material.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Jemy Academy',
      'dashboard': 'Dashboard',
      'my_courses': 'My Courses',
      'certificates': 'Certificates',
      'subscriptions': 'Subscriptions',
      'settings': 'Settings',
      'logout': 'Logout',
      'continue_learning': 'Continue Learning',
      'new_courses': 'New Courses',
      'popular_categories': 'Popular Categories',
      'see_all': 'See All',
      'hours': 'Hours',
      'by': 'By',
      'new': 'NEW',
      'latest_articles': 'Latest Articles',
      'dark_mode': 'Dark Mode',
      'toggle_theme': 'Toggle application theme',
      'language': 'Language',
      'current_language': 'English',
      'account_details': 'Account Details',
      'welcome_back': 'Welcome back, Student!',
      'active_courses': 'Active Courses',
      'hours_watched': 'Hours Watched',
      'avg_score': 'Avg Score',
      'recent_activity': 'Recent Activity',
      'course_progress': 'Course Progress',
      'course_syllabus': 'Course Syllabus',
      'premium_member': 'Premium Member',
      'status': 'Status',
      'active': 'Active',
      'expires_on': 'Expires On',
      'renew': 'Renew Subscription',
      'my_certificates': 'My Certificates',
      'completed': 'Completed',
      'locked': 'Locked',
      'download': 'Download',
    },
    'ar': {
      'app_title': 'أكاديمية جيمي',
      'dashboard': 'لوحة التحكم',
      'my_courses': 'دوراتي',
      'certificates': 'الشهادات',
      'subscriptions': 'الاشتراكات',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'continue_learning': 'متابعة التعلم',
      'new_courses': 'كورسات جديدة',
      'popular_categories': 'أقسام شائعة',
      'see_all': 'عرض الكل',
      'hours': 'ساعات',
      'by': 'بواسطة',
      'new': 'جديد',
      'latest_articles': 'أحدث المقالات',
      'dark_mode': 'الوضع المظلم',
      'toggle_theme': 'تغيير مظهر التطبيق',
      'language': 'اللغة',
      'current_language': 'العربية',
      'account_details': 'تفاصيل الحساب',
      'welcome_back': 'مرحباً بك مجدداً!',
      'active_courses': 'كورسات نشطة',
      'hours_watched': 'ساعات المشاهدة',
      'avg_score': 'متوسط الدرجات',
      'recent_activity': 'أحدث النشاطات',
      'course_progress': 'نسبة الإنجاز',
      'course_syllabus': 'منهج الكورس',
      'premium_member': 'عضو مميز',
      'status': 'الحالة',
      'active': 'نشط',
      'expires_on': 'تاريخ الانتهاء',
      'renew': 'تجديد الاشتراك',
      'my_certificates': 'شهاداتي',
      'completed': 'مكتمل',
      'locked': 'مغلق',
      'download': 'تحميل',
    }
  };

  static String tr(BuildContext context, String key) {
    // We fetch the Locale from the nearest LocaleProvider via Provider in UI, or directly from the Localizations widget.
    // For simplicity with our custom provider, we will use the Localizations.localeOf(context).languageCode
    final locale = Localizations.localeOf(context).languageCode;
    return _translations[locale]?[key] ?? key;
  }
}
